defaultHeaders<-function(token){
c('Accept'='*/*','Content-Type'='application/json','Authorization'=paste('Bearer',token))}
itemsUrl<-function(url,repo_name){
paste0(url,'/api/repos/',repo_name,'/items')}
getToken<-function(pia_url,app_key,app_secret){
auth_url<-paste0(pia_url,'/oauth/token')
optTimeout<-RCurl::curlOptions(connecttimeout=10)
response<-tryCatch(
RCurl::postForm(auth_url,client_id=app_key,client_secret=app_secret,grant_type='client_credentials',.opts=optTimeout),
error=function(e){return(NA)})
if(is.na(response)){
return(NA)
}else{
if(jsonlite::validate(response[1])){
return(rjson::fromJSON(response[1])$access_token)
}else{
return(NA)}}}
setupApp<-function(pia_url,app_key,app_secret){
app_token<-getToken(pia_url,app_key,app_secret)
if(is.na(app_token)){
vector()
}else{
c('url'=pia_url,'app_key'=app_key,'app_secret'=app_secret,'token'=app_token)}}
r2d<-function(response){
if(is.na(response)){
data.frame()
}else{
if(nchar(response)>0){
retVal<-rjson::fromJSON(response)
if(length(retVal)==0){
data.frame()
}else{
if('error'%in%names(retVal)){
data.frame()
}else{
if(!is.null(retVal$message)){
if(retVal$message=='error.accessDenied'){
 data.frame()
}else{
 do.call(rbind,lapply(retVal,data.frame))}
}else{
do.call(rbind,lapply(retVal,data.frame))}}}
}else{
data.frame()}}}
readItems<-function(app,repo_url){
if(length(app)==0){
data.frame()
return()}
headers<-defaultHeaders(app[['token']])
url_data<-paste0(repo_url,'?size=2000')
header<-RCurl::basicHeaderGatherer()
doc<-tryCatch(
RCurl::getURI(url_data,.opts=list(httpheader=headers),headerfunction=header$update),
error=function(e){return(NA)})
response<-NA
respData<-data.frame()
if(!is.na(doc)){
recs<-tryCatch(
as.integer(header$value()[['X-Total-Count']]),
error=function(e){return(0)})
if(recs>2000){
for(page in 0:floor(recs/2000)){
url_data<-paste0(repo_url,'?page=',page,'&size=2000')
response<-tryCatch(
RCurl::getURL(url_data,.opts=list(httpheader=headers)),
error=function(e){return(NA)})
subData<-r2d(response)
if(nrow(respData)>0){
respData<-rbind(respData,subData)
}else{
respData<-subData}}
}else{
response<-tryCatch(
RCurl::getURL(url_data,.opts=list(httpheader=headers)),
error=function(e){return(NA)})
respData<-r2d(response)}}
respData}
pia_url<-'[pia_url]'
app_key<-'[app_key]'
app_secret<-'[app_secret]'
app<-setupApp(pia_url,app_key,app_secret)
url<-itemsUrl(pia_url,app_key)
items<-readItems(app,url)
raw<-paste(apply(head(items[order(as.Date(items$date,format="%Y-%m-%d"),decreasing=TRUE),c('date','value')],3),1,function(x) paste(x,collapse=': ')),collapse='<br>')
result <- utf8ToInt(paste(raw, collapse = '<br>'))